spring:
  application:
    name: microservice-b
  redis:
    lettuce:
      pool:
        # 连接池最大连接数(使用负值表示没有限制) 默认为8
        max-active: 8
        # 连接池中的最大空闲连接 默认为8
        max-idle: 8
        # 连接池中的最小空闲连接 默认为 0
        min-idle: 0
        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
        max-wait: -1
        # 空闲连接关闭时间
        time-between-eviction-runs: 1000
    host: 127.0.0.1
    port: 6379
server:
  port: 9011
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
